# list of plugins to install on a given Jenkins server
default['oe-jenkins']['plugins'] = 
  %w(
    ant
    artifactory
    build-pipeline-plugin
    cobertura
    conditional-buildstep
    copyartifact
    credentials
    cvs
    envinject
    external-monitor-job
    git
    git-client
    github
    github-api
    github-oauth
    git-parameter
    gradle
    greenballs
    htmlpublisher
    javadoc
    ldap
    m2release
    mailer
    maven-plugin
    pam-auth
    parameterized-trigger
    promoted-builds
    run-condition
    scm-api
    sonar
    ssh-agent
    ssh-credentials
    ssh-slaves
    subversion
    thinBackup
    throttle-concurrents
    token-macro
    translation
  )
