name		 'salesforce'
maintainer	 'Analía Lorenzatto'
maintainer_email 'analia.lorenzatto@openenglish.com'
license          'All rights reserved'
description      'Installs/Configures salesforce'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          '0.0.2'
depends		 'oe-tomcat'
depends          'apt'
depends		 'oe-logs' 
depends		 'oe-apache2'
