name             'pp2-store2'
maintainer       'Hernan Dominguez'
maintainer_email 'hernan.dominguez@openenglish.com'
license          'All rights reserved'
description      'Installs/Configures pp2-store2'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          '0.0.1'
depends          'apache2'
depends          'apt'
depends          'tomcat'
depends          'monit'
depends          'datadog'
depends			 'oe-tomcat'
