name             'lp2-db'
maintainer       'Miguel Landaeta'
maintainer_email 'miguel@openenglish.com'
license          'All rights reserved'
description      'Installs/Configures lp2-db'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          '0.1.0'
depends          'postgresql'
depends          'monit'
depends          'datadog'
