name             'lp2-ins'
maintainer       'Miguel Landaeta'
maintainer_email 'miguel@openenglish.com'
license          'All rights reserved'
description      'Installs/Configures lp2-ins'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          '0.1.4'
depends          'apt'
depends          'tomcat'
depends          'monit'
depends          'datadog'
